/**
 * SkyscannerApiClient
 * Java api client for skyscanner API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.mallorcasoftware.skyscannerapiclient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.mallorcasoftware.skyscannerapiclient.model.CarrierDto;
import com.mallorcasoftware.skyscannerapiclient.model.CurrencyDto;
import com.mallorcasoftware.skyscannerapiclient.model.PlaceDto;
import com.mallorcasoftware.skyscannerapiclient.model.QuoteDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * BrowseQuotesResponseDto
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-30T14:30:56.539+02:00")
public class BrowseQuotesResponseDto   {
  @SerializedName("Quotes")
  private List<QuoteDto> quotes = new ArrayList<QuoteDto>();

  @SerializedName("Places")
  private List<PlaceDto> places = new ArrayList<PlaceDto>();

  @SerializedName("Carriers")
  private List<CarrierDto> carriers = new ArrayList<CarrierDto>();

  @SerializedName("Currencies")
  private List<CurrencyDto> currencies = new ArrayList<CurrencyDto>();

  public BrowseQuotesResponseDto quotes(List<QuoteDto> quotes) {
    this.quotes = quotes;
    return this;
  }

  public BrowseQuotesResponseDto addQuotesItem(QuoteDto quotesItem) {
    this.quotes.add(quotesItem);
    return this;
  }

   /**
   * Get quotes
   * @return quotes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<QuoteDto> getQuotes() {
    return quotes;
  }

  public void setQuotes(List<QuoteDto> quotes) {
    this.quotes = quotes;
  }

  public BrowseQuotesResponseDto places(List<PlaceDto> places) {
    this.places = places;
    return this;
  }

  public BrowseQuotesResponseDto addPlacesItem(PlaceDto placesItem) {
    this.places.add(placesItem);
    return this;
  }

   /**
   * Get places
   * @return places
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<PlaceDto> getPlaces() {
    return places;
  }

  public void setPlaces(List<PlaceDto> places) {
    this.places = places;
  }

  public BrowseQuotesResponseDto carriers(List<CarrierDto> carriers) {
    this.carriers = carriers;
    return this;
  }

  public BrowseQuotesResponseDto addCarriersItem(CarrierDto carriersItem) {
    this.carriers.add(carriersItem);
    return this;
  }

   /**
   * Get carriers
   * @return carriers
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<CarrierDto> getCarriers() {
    return carriers;
  }

  public void setCarriers(List<CarrierDto> carriers) {
    this.carriers = carriers;
  }

  public BrowseQuotesResponseDto currencies(List<CurrencyDto> currencies) {
    this.currencies = currencies;
    return this;
  }

  public BrowseQuotesResponseDto addCurrenciesItem(CurrencyDto currenciesItem) {
    this.currencies.add(currenciesItem);
    return this;
  }

   /**
   * Get currencies
   * @return currencies
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<CurrencyDto> getCurrencies() {
    return currencies;
  }

  public void setCurrencies(List<CurrencyDto> currencies) {
    this.currencies = currencies;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrowseQuotesResponseDto browseQuotesResponseDto = (BrowseQuotesResponseDto) o;
    return Objects.equals(this.quotes, browseQuotesResponseDto.quotes) &&
        Objects.equals(this.places, browseQuotesResponseDto.places) &&
        Objects.equals(this.carriers, browseQuotesResponseDto.carriers) &&
        Objects.equals(this.currencies, browseQuotesResponseDto.currencies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quotes, places, carriers, currencies);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrowseQuotesResponseDto {\n");
    
    sb.append("    quotes: ").append(toIndentedString(quotes)).append("\n");
    sb.append("    places: ").append(toIndentedString(places)).append("\n");
    sb.append("    carriers: ").append(toIndentedString(carriers)).append("\n");
    sb.append("    currencies: ").append(toIndentedString(currencies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

