/**
 * SkyscannerApiClient
 * Java api client for skyscanner API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.mallorcasoftware.skyscannerapiclient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * CurrencyDto
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-30T14:30:56.539+02:00")
public class CurrencyDto   {
  @SerializedName("Code")
  private String code = null;

  @SerializedName("Symbol")
  private String symbol = null;

  @SerializedName("ThousandsSeparator")
  private String thousandsSeparator = null;

  @SerializedName("DecimalSeparator")
  private String decimalSeparator = null;

  @SerializedName("SymbolOnLeft")
  private Boolean symbolOnLeft = null;

  @SerializedName("SpaceBetweenAmountAndSymbol")
  private Boolean spaceBetweenAmountAndSymbol = null;

  @SerializedName("RoundingCoefficient")
  private Integer roundingCoefficient = null;

  @SerializedName("DecimalDigits")
  private Integer decimalDigits = null;

  public CurrencyDto code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public CurrencyDto symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public CurrencyDto thousandsSeparator(String thousandsSeparator) {
    this.thousandsSeparator = thousandsSeparator;
    return this;
  }

   /**
   * Get thousandsSeparator
   * @return thousandsSeparator
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getThousandsSeparator() {
    return thousandsSeparator;
  }

  public void setThousandsSeparator(String thousandsSeparator) {
    this.thousandsSeparator = thousandsSeparator;
  }

  public CurrencyDto decimalSeparator(String decimalSeparator) {
    this.decimalSeparator = decimalSeparator;
    return this;
  }

   /**
   * Get decimalSeparator
   * @return decimalSeparator
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDecimalSeparator() {
    return decimalSeparator;
  }

  public void setDecimalSeparator(String decimalSeparator) {
    this.decimalSeparator = decimalSeparator;
  }

  public CurrencyDto symbolOnLeft(Boolean symbolOnLeft) {
    this.symbolOnLeft = symbolOnLeft;
    return this;
  }

   /**
   * Get symbolOnLeft
   * @return symbolOnLeft
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSymbolOnLeft() {
    return symbolOnLeft;
  }

  public void setSymbolOnLeft(Boolean symbolOnLeft) {
    this.symbolOnLeft = symbolOnLeft;
  }

  public CurrencyDto spaceBetweenAmountAndSymbol(Boolean spaceBetweenAmountAndSymbol) {
    this.spaceBetweenAmountAndSymbol = spaceBetweenAmountAndSymbol;
    return this;
  }

   /**
   * Get spaceBetweenAmountAndSymbol
   * @return spaceBetweenAmountAndSymbol
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSpaceBetweenAmountAndSymbol() {
    return spaceBetweenAmountAndSymbol;
  }

  public void setSpaceBetweenAmountAndSymbol(Boolean spaceBetweenAmountAndSymbol) {
    this.spaceBetweenAmountAndSymbol = spaceBetweenAmountAndSymbol;
  }

  public CurrencyDto roundingCoefficient(Integer roundingCoefficient) {
    this.roundingCoefficient = roundingCoefficient;
    return this;
  }

   /**
   * Get roundingCoefficient
   * @return roundingCoefficient
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getRoundingCoefficient() {
    return roundingCoefficient;
  }

  public void setRoundingCoefficient(Integer roundingCoefficient) {
    this.roundingCoefficient = roundingCoefficient;
  }

  public CurrencyDto decimalDigits(Integer decimalDigits) {
    this.decimalDigits = decimalDigits;
    return this;
  }

   /**
   * Get decimalDigits
   * @return decimalDigits
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDecimalDigits() {
    return decimalDigits;
  }

  public void setDecimalDigits(Integer decimalDigits) {
    this.decimalDigits = decimalDigits;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CurrencyDto currencyDto = (CurrencyDto) o;
    return Objects.equals(this.code, currencyDto.code) &&
        Objects.equals(this.symbol, currencyDto.symbol) &&
        Objects.equals(this.thousandsSeparator, currencyDto.thousandsSeparator) &&
        Objects.equals(this.decimalSeparator, currencyDto.decimalSeparator) &&
        Objects.equals(this.symbolOnLeft, currencyDto.symbolOnLeft) &&
        Objects.equals(this.spaceBetweenAmountAndSymbol, currencyDto.spaceBetweenAmountAndSymbol) &&
        Objects.equals(this.roundingCoefficient, currencyDto.roundingCoefficient) &&
        Objects.equals(this.decimalDigits, currencyDto.decimalDigits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, symbol, thousandsSeparator, decimalSeparator, symbolOnLeft, spaceBetweenAmountAndSymbol, roundingCoefficient, decimalDigits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrencyDto {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    thousandsSeparator: ").append(toIndentedString(thousandsSeparator)).append("\n");
    sb.append("    decimalSeparator: ").append(toIndentedString(decimalSeparator)).append("\n");
    sb.append("    symbolOnLeft: ").append(toIndentedString(symbolOnLeft)).append("\n");
    sb.append("    spaceBetweenAmountAndSymbol: ").append(toIndentedString(spaceBetweenAmountAndSymbol)).append("\n");
    sb.append("    roundingCoefficient: ").append(toIndentedString(roundingCoefficient)).append("\n");
    sb.append("    decimalDigits: ").append(toIndentedString(decimalDigits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

