/**
 * SkyscannerApiClient
 * Java api client for skyscanner API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.mallorcasoftware.skyscannerapiclient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * LegDto
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-30T14:32:54.673+02:00")
public class LegDto   {
  @SerializedName("CarrierIds")
  private List<Integer> carrierIds = new ArrayList<Integer>();

  @SerializedName("OriginId")
  private Integer originId = null;

  @SerializedName("DestinationId")
  private Integer destinationId = null;

  @SerializedName("DepartureDate")
  private String departureDate = null;

  public LegDto carrierIds(List<Integer> carrierIds) {
    this.carrierIds = carrierIds;
    return this;
  }

  public LegDto addCarrierIdsItem(Integer carrierIdsItem) {
    this.carrierIds.add(carrierIdsItem);
    return this;
  }

   /**
   * Get carrierIds
   * @return carrierIds
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Integer> getCarrierIds() {
    return carrierIds;
  }

  public void setCarrierIds(List<Integer> carrierIds) {
    this.carrierIds = carrierIds;
  }

  public LegDto originId(Integer originId) {
    this.originId = originId;
    return this;
  }

   /**
   * Get originId
   * @return originId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getOriginId() {
    return originId;
  }

  public void setOriginId(Integer originId) {
    this.originId = originId;
  }

  public LegDto destinationId(Integer destinationId) {
    this.destinationId = destinationId;
    return this;
  }

   /**
   * Get destinationId
   * @return destinationId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDestinationId() {
    return destinationId;
  }

  public void setDestinationId(Integer destinationId) {
    this.destinationId = destinationId;
  }

  public LegDto departureDate(String departureDate) {
    this.departureDate = departureDate;
    return this;
  }

   /**
   * Get departureDate
   * @return departureDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDepartureDate() {
    return departureDate;
  }

  public void setDepartureDate(String departureDate) {
    this.departureDate = departureDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegDto legDto = (LegDto) o;
    return Objects.equals(this.carrierIds, legDto.carrierIds) &&
        Objects.equals(this.originId, legDto.originId) &&
        Objects.equals(this.destinationId, legDto.destinationId) &&
        Objects.equals(this.departureDate, legDto.departureDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(carrierIds, originId, destinationId, departureDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegDto {\n");
    
    sb.append("    carrierIds: ").append(toIndentedString(carrierIds)).append("\n");
    sb.append("    originId: ").append(toIndentedString(originId)).append("\n");
    sb.append("    destinationId: ").append(toIndentedString(destinationId)).append("\n");
    sb.append("    departureDate: ").append(toIndentedString(departureDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

