/**
 * SkyscannerApiClient
 * Java api client for skyscanner API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.mallorcasoftware.skyscannerapiclient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.mallorcasoftware.skyscannerapiclient.model.LegDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * QuoteDto
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-30T14:30:56.539+02:00")
public class QuoteDto   {
  @SerializedName("QuoteId")
  private Integer quoteId = null;

  @SerializedName("MinPrice")
  private Integer minPrice = null;

  @SerializedName("Direct")
  private Boolean direct = null;

  @SerializedName("OutboundLeg")
  private LegDto outboundLeg = null;

  @SerializedName("InboundLeg")
  private LegDto inboundLeg = null;

  @SerializedName("QuoteDateTime")
  private String quoteDateTime = null;

  public QuoteDto quoteId(Integer quoteId) {
    this.quoteId = quoteId;
    return this;
  }

   /**
   * Get quoteId
   * @return quoteId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getQuoteId() {
    return quoteId;
  }

  public void setQuoteId(Integer quoteId) {
    this.quoteId = quoteId;
  }

  public QuoteDto minPrice(Integer minPrice) {
    this.minPrice = minPrice;
    return this;
  }

   /**
   * Get minPrice
   * @return minPrice
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMinPrice() {
    return minPrice;
  }

  public void setMinPrice(Integer minPrice) {
    this.minPrice = minPrice;
  }

  public QuoteDto direct(Boolean direct) {
    this.direct = direct;
    return this;
  }

   /**
   * Get direct
   * @return direct
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getDirect() {
    return direct;
  }

  public void setDirect(Boolean direct) {
    this.direct = direct;
  }

  public QuoteDto outboundLeg(LegDto outboundLeg) {
    this.outboundLeg = outboundLeg;
    return this;
  }

   /**
   * Get outboundLeg
   * @return outboundLeg
  **/
  @ApiModelProperty(example = "null", value = "")
  public LegDto getOutboundLeg() {
    return outboundLeg;
  }

  public void setOutboundLeg(LegDto outboundLeg) {
    this.outboundLeg = outboundLeg;
  }

  public QuoteDto inboundLeg(LegDto inboundLeg) {
    this.inboundLeg = inboundLeg;
    return this;
  }

   /**
   * Get inboundLeg
   * @return inboundLeg
  **/
  @ApiModelProperty(example = "null", value = "")
  public LegDto getInboundLeg() {
    return inboundLeg;
  }

  public void setInboundLeg(LegDto inboundLeg) {
    this.inboundLeg = inboundLeg;
  }

  public QuoteDto quoteDateTime(String quoteDateTime) {
    this.quoteDateTime = quoteDateTime;
    return this;
  }

   /**
   * Get quoteDateTime
   * @return quoteDateTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getQuoteDateTime() {
    return quoteDateTime;
  }

  public void setQuoteDateTime(String quoteDateTime) {
    this.quoteDateTime = quoteDateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuoteDto quoteDto = (QuoteDto) o;
    return Objects.equals(this.quoteId, quoteDto.quoteId) &&
        Objects.equals(this.minPrice, quoteDto.minPrice) &&
        Objects.equals(this.direct, quoteDto.direct) &&
        Objects.equals(this.outboundLeg, quoteDto.outboundLeg) &&
        Objects.equals(this.inboundLeg, quoteDto.inboundLeg) &&
        Objects.equals(this.quoteDateTime, quoteDto.quoteDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quoteId, minPrice, direct, outboundLeg, inboundLeg, quoteDateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuoteDto {\n");
    
    sb.append("    quoteId: ").append(toIndentedString(quoteId)).append("\n");
    sb.append("    minPrice: ").append(toIndentedString(minPrice)).append("\n");
    sb.append("    direct: ").append(toIndentedString(direct)).append("\n");
    sb.append("    outboundLeg: ").append(toIndentedString(outboundLeg)).append("\n");
    sb.append("    inboundLeg: ").append(toIndentedString(inboundLeg)).append("\n");
    sb.append("    quoteDateTime: ").append(toIndentedString(quoteDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

