/**
 * SkyscannerApiClient
 * Java api client for skyscanner API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.mallorcasoftware.skyscannerapiclient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * RouteDto
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-30T14:32:54.673+02:00")
public class RouteDto   {
  @SerializedName("OriginId")
  private Integer originId = null;

  @SerializedName("DestinationId")
  private Integer destinationId = null;

  @SerializedName("QuoteIds")
  private List<Integer> quoteIds = new ArrayList<Integer>();

  @SerializedName("Price")
  private Integer price = null;

  @SerializedName("QuoteDateTime")
  private String quoteDateTime = null;

  public RouteDto originId(Integer originId) {
    this.originId = originId;
    return this;
  }

   /**
   * Get originId
   * @return originId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getOriginId() {
    return originId;
  }

  public void setOriginId(Integer originId) {
    this.originId = originId;
  }

  public RouteDto destinationId(Integer destinationId) {
    this.destinationId = destinationId;
    return this;
  }

   /**
   * Get destinationId
   * @return destinationId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDestinationId() {
    return destinationId;
  }

  public void setDestinationId(Integer destinationId) {
    this.destinationId = destinationId;
  }

  public RouteDto quoteIds(List<Integer> quoteIds) {
    this.quoteIds = quoteIds;
    return this;
  }

  public RouteDto addQuoteIdsItem(Integer quoteIdsItem) {
    this.quoteIds.add(quoteIdsItem);
    return this;
  }

   /**
   * Get quoteIds
   * @return quoteIds
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Integer> getQuoteIds() {
    return quoteIds;
  }

  public void setQuoteIds(List<Integer> quoteIds) {
    this.quoteIds = quoteIds;
  }

  public RouteDto price(Integer price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPrice() {
    return price;
  }

  public void setPrice(Integer price) {
    this.price = price;
  }

  public RouteDto quoteDateTime(String quoteDateTime) {
    this.quoteDateTime = quoteDateTime;
    return this;
  }

   /**
   * Get quoteDateTime
   * @return quoteDateTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getQuoteDateTime() {
    return quoteDateTime;
  }

  public void setQuoteDateTime(String quoteDateTime) {
    this.quoteDateTime = quoteDateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteDto routeDto = (RouteDto) o;
    return Objects.equals(this.originId, routeDto.originId) &&
        Objects.equals(this.destinationId, routeDto.destinationId) &&
        Objects.equals(this.quoteIds, routeDto.quoteIds) &&
        Objects.equals(this.price, routeDto.price) &&
        Objects.equals(this.quoteDateTime, routeDto.quoteDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originId, destinationId, quoteIds, price, quoteDateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteDto {\n");
    
    sb.append("    originId: ").append(toIndentedString(originId)).append("\n");
    sb.append("    destinationId: ").append(toIndentedString(destinationId)).append("\n");
    sb.append("    quoteIds: ").append(toIndentedString(quoteIds)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    quoteDateTime: ").append(toIndentedString(quoteDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

